[package]
name = "actionloop"
version = "0.1.0"
authors = ["Zac Blanco <zblanco@ucsd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
log = "0.4"
env_logger = "0.8"
